batch_size: 2
cfg: configs/msnet_base.yaml
epochs: 1000
lr: 0.0001
num_classes: 3
output_folder: !!python/object/apply:pathlib.PosixPath
- /
- raid
- temuuzhin
- src
- msnet
- version_1
- runs
- model
resume: true
seg_folder: !!python/object/apply:pathlib.PosixPath
- runs
- model
- segs
val: 1
weight_decay: 0
workers: 2
