batch_size: 1
cfg: configs/msnet_base.yaml
input: /raid/temuuzhin/src/DATA/Task01_BrainTumour/
model: /raid/temuuzhin/src/togit/msnet/train_results/model3_200/model_best.pth.tar
num_classes: 3
output_folder: !!python/object/apply:pathlib.PosixPath
- /
- raid
- temuuzhin
- src
- togit
- msnet
- test_results
- model3_200
seg_folder: !!python/object/apply:pathlib.PosixPath
- test_results
- model3_200
- output
workers: 2
