accumulation_steps: null
amp_opt_level: O1
batch_size: 3
cache_mode: part
cfg: configs/msnet_base.yaml
devices: '0'
epochs: 200
eval: false
exp_name: logs_base
fold: 0
lr: 0.0001
num_classes: 3
output_folder: !!python/object/apply:pathlib.PosixPath
- /
- raid
- temuuzhin
- src
- msnet
- version_1
- runs
- logs_base
- model1_2
resume: true
seed: 1234
seg_folder_1: !!python/object/apply:pathlib.PosixPath
- runs
- logs_base
- model1_2
- segs
start_epoch: 0
tag: null
throughput: false
use_checkpoint: false
val: 1
weight_decay: 0
workers: 2
zip: false
