batch_size: 1
cfg: configs/msnet_base.yaml
input: ./user_test/in
model: ./train_results/model3_200/model_best.pth.tar
num_classes: 3
output: ./user_test/out
output_folder: !!python/object/apply:pathlib.PosixPath
- /
- raid
- temuuzhin
- src
- togit
- msnet
- user_test
- out
seg_folder: !!python/object/apply:pathlib.PosixPath
- user_test
- out
- output
workers: 2
