batch_size: 2
cfg: configs/msnet_base.yaml
epochs: 200
input: ./data/Task01_BrainTumour/
lr: 0.0001
num_classes: 3
output_folder: !!python/object/apply:pathlib.PosixPath
- /
- raid
- temuuzhin
- src
- togit
- msnet
- train_results
- model
resume: false
seg_folder: !!python/object/apply:pathlib.PosixPath
- train_results
- model
- output
val: 1
weight_decay: 0
workers: 2
