batch_size: 1
cfg: configs/msnet_base.yaml
num_classes: 3
output_folder: !!python/object/apply:pathlib.PosixPath
- /
- raid
- temuuzhin
- src
- togit
- msnet
- test_results
- model_sw
seg_folder: !!python/object/apply:pathlib.PosixPath
- test_results
- model_sw
- output
workers: 2
