batch_size: 3
cfg: configs/msnet_base.yaml
epochs: 200
lr: 0.0001
num_classes: 3
output_folder: !!python/object/apply:pathlib.PosixPath
- /
- raid
- temuuzhin
- src
- msnet
- version_1
- runs
- model_1modw
resume: false
seg_folder: !!python/object/apply:pathlib.PosixPath
- runs
- model_1modw
- segs
val: 1
weight_decay: 0
workers: 2
